[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "2db61343dba1e455f35846b7758157914990487d"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "042c655e2e9c9cb89c4385f31ccc1395a8f911d18c6ffb1f9fbbcece10e1f966"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "119e36fa593b51ca78f43e33cb6578972bb46522"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "9bd01c3df7ab0d2a5fcd63fb71064bd389eea36dfde090cc28ef943913e9497c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "0963184f4c407fa3f90dd464e2d80b55da743bf6"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "c8fb6ff03090dade850cf76421a79d629c7aaff17864adfb9ff792638013de77"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "00253ef2e9880a01dbcdc95634d6dd5891d850fe"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "8869e96e01da5a188a20347dc6e9b65a38b0517e347c75c75eb82342299539ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "323b7e2d3e74cbe261ef61ef26d7cc506131c602"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "568213858ae794e9e7c013141963cf1bf77ca293667396c31cec36c00187f486"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "40ddfcbf66c465da80c5a34cd5289917f85792a7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "5306c5ed3711b34303c3527d8db9df380fd7c0ceab6b03d5346515db44204f97"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "e4796c5d67c05848e204dd495705e2a511b9e0bc"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "7211162d76f328d72755e9a242b5dd43bb07d063ba036e0f7a2cd85cfd68fd6d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "27136cc68a672026ba9c458b0472e4be5f80adce"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "d658101cb5a8ca98b0d0770a71ed8b6f50363e287deb138fe4dd4d79918a94c6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+1/GAP_pkg_digraphs.v100.500.300.x86_64-unknown-freebsd.tar.gz"
