[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "ea2f784ec733b4ae7f490bdcca3ea9b1ca452608"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "7f35642265f8da64163e1c3879fddbe12557f42157c4d5d03089f73111b2ad8b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "a82ca6af8acddcd9ab72094e08abaaf85b00987e"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "7ed7aed6cff994958c792ffb6db5acb02cc6390272b927c683d10999c013aceb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "83c06b806273ff60d3e14dd4a388e1b800973f90"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "7e9f873f6251f64ce910ac9721afb693be22a565c1cd9e9886c081eaffb07bff"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "6214874c0670f4bce31bd05c34738e432a35ba1d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "ac42ee09901bd7a33e6372b29c1b49bd2374f45f47c7a8081af9172f0f20a5c6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "b3b29c4b10122670bffcefaf68e6c5e2d3003ca9"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "581fa400be37f8bc4f8b27f03c91189f4caea8554168be7da39e92d47b745d83"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "da6952e531ba934c424be224102875323024f350"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "86dd09c55510584deae62f44bc1ee06b453f84e9e848d087392fea5bb9806054"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "1420a7645061fcb04cb7daa69c2861a7c8e6aa50"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "ca7f74c2862a4dd9893e6a803104208de1439cd6fec21d4a158abd9ea5bc1cc8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "41aee727c8b44154d3a464bf2288e3f7d7cf278f"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "745d5dcb37e40c0f08f4b915233d51608b764a1d4f34f7f676760c421f6b7ec5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.100+0/GAP_pkg_digraphs.v100.600.100.x86_64-unknown-freebsd.tar.gz"
