[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "76f6b068d0d7cda804548ebf37ac0f93317d0fa7"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "bc70effc2676137342fbfab1c011face13a91cb04d67cde4542113b9edb1b929"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "dfda9fee07d2f600f51e5fa8d663db30f0b735b7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "ff97285b063fae0566a8dde49df6048d5f9fb0cf4a2284b6921a8f26af7cdd27"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "057ac4f69f1b9469ec81bfaf8c3412ef8d362d93"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "6d222e57e0d397583601f3aaed45c245567b0234dfa2971bb5311229649bd9fa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "21bc3e88d76428f0129c2abc4dbc2c8dd31c435a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "629241603eb1adf65b8026fa59967d5f4be5207f7cea507654318c864384d633"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "aaed007114cdeb82730d3e07e86ab072e82f3ba6"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "54b332598eb949a3653d9ec200384813ea13e7cb5b8959de9c8a047029a43569"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "4ba6097b9e801948086c7a261d65ddc114bb5325"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "2fde22482c21dc07151c7830a729e98fbbadc9a900b5da6bcf6fb8ce012dd210"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "f4fcd7317cd79d7c132d195613ae0d1928ef3ffe"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "706d65a65c93c1d0e22502af65bec31729499b3dd050defd1c964727cadecc32"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "d064738e14a6aa76a88a5759e508dc034c4e9b43"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "0a4e952fa3b86e8d41b290b5c035910869cc02a4e9de5535409ad7d9b901f78c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.900.0+0/GAP_pkg_digraphs.v100.900.0.x86_64-unknown-freebsd.tar.gz"
