[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "938057a3f3144cfd75b4a3c289132eccf08016aa"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "00983bc7f04fc37eeeb54e8574da39dc2ab2eea53e8555ee0754800e598e8646"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "7a7043ee9d9b1024736d745de55b720b8195c459"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "3b6633a718fbd49d5f78302e462d3e20629433da0f1be82cca62cdf365b30f9a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "7248c9a07b053285596b0b40487b2009c20ab60a"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "bd151950705602121f4f08e64c5f1fe2164bdbdc0186b3c4551459bef536babc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "657916816af89ef4ffb2e53b160d161fad2b6172"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "4dd2563b049f5ff5cdab6b07ba81648e5697c08478734726038da838079db151"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "2f43f4390de691d00a126015115a73784f51e1af"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "8a27de1f6c7ae0c8e0b3fe8af071c831a4995cadde738426ad1cca1229e00b05"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "18f8fbf75fd2c28902580e28ede55c16c8134bb7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "e9f84a797464ce1a82c243088c25329e37feb86ab6424d50766db652db5e6e1a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "84b552f658788a0ea4229f12e06290a3144f9967"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "6858d629c93ada5a7ec6a4f95670afa668776d085c27fde3596c911edd435a5a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "f28f7aadeacfe92dbb63d004eeaadd3ab56b718a"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "54b58293f7ebd747073353b21461c3056a111391aeba14a4c242f35db9c47ba5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.700.100+0/GAP_pkg_digraphs.v100.700.100.x86_64-unknown-freebsd.tar.gz"
