[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "92ad8375169a4b34796b37b6a8bd3d3542c4e32a"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "50712002c9e6a410fa74148130c7add6513a556e4191a911c09cc22451a3b7af"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "b705e288762cdc71d3890ff6351409560c014433"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "aff52e6a270702c70a46781fc3ea06ddb985f15e4a2152f3534d953233cc3b30"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "e4f05917f6ebd0b2754e56d46f912ddc50f61153"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "835fd05defb504b51046d2a415bdd489d60cd72f43697eb00b536263a51e8189"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "abb6df4621f99c6af40c46c357f6f4cfbef1f628"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "c0257642b5d53129ce2599b71d92201f73ce3c745b8ccba839f28a610b93f301"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "fe6ccbdb05f6669fd2d468cff1ee58c7d3f41124"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "1d6b430032a594a89ffc54ce4e63a5f8a7e727b614db7393b1414f3f4f688945"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "c59e7d1527c3941fa5cd7385e0b380a618f1c55a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "e388b248b5934c50cf2052de74b34b6a57db2ae311959c768621eda5490f7cf6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "4766c61876c1e3eeb616701fa155e25fcf49f76f"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "fd4ee0e5b961791dd374974ea9c8a6ecacf4948a1327617b3b0829d09c9545a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "f58b38c2f12b203db58c57ef97226ad7f8807350"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "b6204908899704d12c755504b934a44b822a955a7a97dc6a6aae997fd3c685bf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.600.0+1/GAP_pkg_digraphs.v100.600.0.x86_64-unknown-freebsd.tar.gz"
