[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "eea8389ae492ee9efd1c932831cb81248e3059be"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "80f2a367915ad78a85624edb7e766cc7d7af311267ee8f0e5c0a214910f0cd3b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "8d968c93fece804cc1a546f3fa894d4b844ec412"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "bbe436eb6af358c6e88d4377ca2f87f5206db207c110e1a8fea9a58fc9b0e446"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "bc0bad1daa7a68522e276fe75e66b4a7bcb59d34"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "9e19d222e5bfc84a4c247e9ebd9616aafa07b61a89af49680a8bdc8d8f35d26c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "f32951e200f2bd1d81a56537ae48447997f56120"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "f6b3b92c59c3fc55412d5ed3ce53da71938160e5de2599069cd44f7ce8be0518"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "e293c348d42a522c3985c10173df82e0222a0c37"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "83b71fec00a4b4bad65639fdfa5b6beb9f692255d4712a31a70ebf62b62083f2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "429162631252d2282daa4402a01fb9afe7a8041d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "7c9967ca2274458bb9e5e3c3e4f491d10466fe21c0aebb0b1f16efc1c6a6cbe6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "2edf46fb6a799a48772e94e91eb62d11b5fd89f8"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "b7747b9e85d25d6d13896478a012c249b752650adc265d350204777189b10406"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "79cd13c5c51646181b8b42a7fc7e1e4e606081b1"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "e1c106f824fece4f1df585af08f75eccd8a71e0a4cdaf0dc190246725ef79663"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.500.300+0/GAP_pkg_digraphs.v100.500.300.x86_64-unknown-freebsd.tar.gz"
