[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "e195e6ec14ae8278ee3195646eb90c0757464dfd"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "dc2479b708809b082ec257c5eccb0fcfd1a4955612b75368b7e86fee8491ee1b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "792b257f560b301048e93703c42e2a91e2851bb2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "f4a447b8e16c3805d48cb535df295f275bd74317394e2ede440fc117ca4d4df7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "aarch64"
git-tree-sha1 = "6066e5dd2eac3a5f068320bf50ec94fec38a38df"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "73e8c73149c4cb453b1ae515dc95a6c9f67d7c1ef36449cc9d0e87301df95b01"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.aarch64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "powerpc64le"
git-tree-sha1 = "b4f43db8f30266173683aa154c7e0d37d6e82451"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "b0fa25732fa11e8ffd60156139d0b83d74c4ddd79a8d622d1215a7d78c10dc2d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "fd92de96276c4ba316478fefda18ac5b2712b60c"
os = "macos"

    [[GAP_pkg_digraphs.download]]
    sha256 = "b04cf951bfce0ebfb446cfc6b212f6c981ccdaba16d35964748e1df1703c2902"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "e818073ee5eab4e409f9350776e36fd0e23b5afd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "f6c10c93d23d5676d35a1e03b6cb362a2a2ee8c5a519218f21094aed4d820a31"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "fab8d68173a79a15b3921a33448257e4e52fdf75"
libc = "musl"
os = "linux"

    [[GAP_pkg_digraphs.download]]
    sha256 = "fcef43acd8060c9083c949ab7d7a763fe3f804f540cfae1905a6384ad9323e07"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.x86_64-linux-musl.tar.gz"
[[GAP_pkg_digraphs]]
arch = "x86_64"
git-tree-sha1 = "ae62dca06590ce5c7fb8b7a409b95a288841a400"
os = "freebsd"

    [[GAP_pkg_digraphs.download]]
    sha256 = "12545280882f86f818d885894de68c01147c81c3644f4da5708b2dff5b4949b8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_digraphs_jll.jl/releases/download/GAP_pkg_digraphs-v100.400.101+0/GAP_pkg_digraphs.v100.400.101.x86_64-unknown-freebsd.tar.gz"
